# SQLite 資料庫
spring.datasource.url=jdbc:sqlite:miniclinic.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Hibernate SQLite 方言
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# 自動更新資料表
spring.jpa.hibernate.ddl-auto=update

# 顯示 SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# data.sql 設定
spring.sql.init.encoding=UTF-8
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always